### Test del registro de usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Adrian",
  "email": "test@test.com",
  "password": "12345678",
  "confirmPassword": "12345678"
}

### Test del inicio de sesión del usuario
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}